# YML CI for Azure Devops
# Author: Abbi Reddy Cheemala
# Date: 24-02-2020
# Description: Print Hello world!
# Organization: Aabvin Solutions Pvt Ltd.

# Run pipeline whenever a commit or tag is pushed to 
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Put the version for the CI pipeline
variables:
  major: 1
  minor: 1

name: $(major).$(minor)$(Rev:.r)
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'